In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

np.set_printoptions(suppress=True, precision=4)


### Notes: 

$A\mathbf{x} = \mathbf{b}$ -> has exactly one solution for this space $\mathbf{x} = A^{-1}b$

In [2]:
A = np.array([[2,3,1],[2,4,1],[3,7,1]])
A

array([[2, 3, 1],
       [2, 4, 1],
       [3, 7, 1]])

Invertible Matrix

In [3]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 3., -4.,  1.],
       [-1.,  1., -0.],
       [-2.,  5., -2.]])

Dot product of the original matrix and its inverse should produce an identity matrix

In [4]:
A @ A_inv

array([[ 1., -0.,  0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])

#### Using `solve`

This is the more computationally efficient way, as matrices grow in size

In [5]:
n = A.shape[0]
n

3

In [6]:
A_id = np.eye(n)

In [7]:
np.linalg.solve(A, A_id)

array([[ 3., -4.,  1.],
       [-1.,  1., -0.],
       [-2.,  5., -2.]])

Row reduced echelon form

In [8]:
A = np.array([[1, 2, 5], [1, 2, 5], [1, 2, 5]])
A

array([[1, 2, 5],
       [1, 2, 5],
       [1, 2, 5]])

$A = CR$

In [9]:
C = np.array([[1], [1], [1]])
R = np.array([[1, 2, 5]])

In [10]:
C

array([[1],
       [1],
       [1]])

In [11]:
R

array([[1, 2, 5]])

In [12]:
C @ R

array([[1, 2, 5],
       [1, 2, 5],
       [1, 2, 5]])

Actaul RREF

In [13]:
zeros_rows = np.zeros((2, R.shape[1]))
zeros_rows

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
R_rref = np.vstack((R, zeros_rows))
R_rref

array([[1., 2., 5.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
A @ R_rref

array([[1., 2., 5.],
       [1., 2., 5.],
       [1., 2., 5.]])

**Problems for Lecture 1 (from textbook Section I.1)**

1. Give an example where a combination of three nonzero vectors in $\mathbb{R}^4$ is the zero vector. Then write your example in the form $A\mathbf{x} = \mathbf{0}$. What are the shapes of $A$ and $\mathbf{x}$ and $\mathbf{0}$?

4. Suppose $A$ is the $3 \times 3$ matrix $\text{ones}(3, 3)$ of all ones. Find two independent vectors $\mathbf{x}$ and $\mathbf{y}$ that solve $A\mathbf{x} = \mathbf{0}$ and $A\mathbf{y} = \mathbf{0}$. Write that first equation $A\mathbf{x} = \mathbf{0}$ (with numbers) as a combination of the columns of $A$. Why don't I ask for a third independent vector with $A\mathbf{z} = \mathbf{0}$?

9. Suppose the column space of an $m \times n$ matrix is all of $\mathbb{R}^3$. What can you say about $m$? What can you say about $n$? What can you say about the rank $r$?

18. If $A = CR$, what are the $CR$ factors of the matrix $A^T$?

#### 1.

In [16]:
v1 = np.ones(3)
v2 = np.ones(3)
v3 = np.ones(3)
v4 = np.ones(3)

In [17]:
A = np.vstack(([v1,v2,v3, v4]))
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
x = np.array([[1,-1,0]])
x

array([[ 1, -1,  0]])

In [19]:
x.T

array([[ 1],
       [-1],
       [ 0]])

In [20]:
A @ x.T

array([[0.],
       [0.],
       [0.],
       [0.]])

#### Answer:

In [21]:
A @ x.T == 0

array([[ True],
       [ True],
       [ True],
       [ True]])

***

#### 2.

4. Suppose $A$ is the $3 \times 3$ matrix $\text{ones}(3, 3)$ of all ones. Find two independent vectors $\mathbf{x}$ and $\mathbf{y}$ that solve $A\mathbf{x} = \mathbf{0}$ and $A\mathbf{y} = \mathbf{0}$. Write that first equation $A\mathbf{x} = \mathbf{0}$ (with numbers) as a combination of the columns of $A$. Why don't I ask for a third independent vector with $A\mathbf{z} = \mathbf{0}$?

In [22]:
A = np.ones((3, 3))
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
x[:, 1] = -2
x

array([[ 1, -2,  0]])

In [24]:
x = np.array([[0,1,-1]]).T
x

array([[ 0],
       [ 1],
       [-1]])

In [25]:
A @ x

array([[0.],
       [0.],
       [0.]])

Answer 1

In [26]:
A @ x == 0

array([[ True],
       [ True],
       [ True]])

In [27]:
y = np.array([[1,0,-1]]).T
y

array([[ 1],
       [ 0],
       [-1]])

In [28]:
A @ y

array([[0.],
       [0.],
       [0.]])

Answer 2

In [29]:
A @ y == 0

array([[ True],
       [ True],
       [ True]])

Answer 3: Z is not asked for because any of the remainder would be linear combinations of the other 2

***


9. Suppose the column space of an $m \times n$ matrix is all of $\mathbb{R}^3$. What can you say about? What can you say about $n$? What can you say about the rank $r$?

If the column space of m x n matrix is $\mathbb{R}^3$, then the dimension of the column and row spaces are $\geq$ rank, which is 3 

***

18. If $A = CR$, what are the $CR$ factors of the matrix $A^T$?

In [30]:
np.random.randint(0, 11, size=(3,3))

array([[ 1, 10,  6],
       [ 4,  4,  7],
       [ 1, 10,  9]])

In [31]:
A 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

***

## Problem I.1.2


$z = c (x - y)$, one candidate is always the zero vector $z=0$ (from the choice $c=0$)

***

## Problem I.1.3

Matrix level: $Ac = \begin{bmatrix} a_1 & \cdots & a_n \end{bmatrix} c = 0$


Scalar level: $\sum_{j=1}^n a_{ij}c_j = 0 \text{ for each row } i = 1, 2, \ldots, m \text{ of } A.$

$$
A = \begin{bmatrix}
a_{11} & a_{12} & a_{13} & a_{14} \
a_{21} & a_{22} & a_{23} & a_{24} \
a_{31} & a_{32} & a_{33} & a_{34}
\end{bmatrix}
\quad
c = \begin{bmatrix}
c_1 \
c_2 \
c_3 \
c_4
\end{bmatrix}
$$
Here, m = 3 (number of rows in A) and n = 4 (number of columns in A and elements in c).
Now, let's look at the matrix multiplication Ac = 0:
$$
Ac = \begin{bmatrix}
a_{11} & a_{12} & a_{13} & a_{14} \
a_{21} & a_{22} & a_{23} & a_{24} \
a_{31} & a_{32} & a_{33} & a_{34}
\end{bmatrix}
\begin{bmatrix}
c_1 \
c_2 \
c_3 \
c_4
\end{bmatrix}
= \begin{bmatrix}
0 \
0 \
0
\end{bmatrix}
$$
Now, let's break this down for each row i:
For i = 1 (first row):
$$\sum_{j=1}^n a_{1j}c_j = a_{11}c_1 + a_{12}c_2 + a_{13}c_3 + a_{14}c_4 = 0$$
For i = 2 (second row):
$$\sum_{j=1}^n a_{2j}c_j = a_{21}c_1 + a_{22}c_2 + a_{23}c_3 + a_{24}c_4 = 0$$
For i = 3 (third row):
$$\sum_{j=1}^n a_{3j}c_j = a_{31}c_1 + a_{32}c_2 + a_{33}c_3 + a_{34}c_4 = 0$$

$$\text{Let } A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix} \text{ and } x = \begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}

\text{The matrix multiplication } Ax \text{ is valid because A is 3x3 and x is 3x1.}

Ax = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix} \begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix} = \begin{bmatrix}
y_1 \\
y_2 \\
y_3
\end{bmatrix}

\text{Using sigma notation, we express each element } y_i \text{ of the resulting vector as:}

y_i = \sum_{j=1}^3 a_{ij}x_j \text{ for } i = 1, 2, 3
$$




$$
\text{Here, } i \text{ represents the row of A, and } j \text{ represents the column of A and the row of x.}

\text{Calculating each } y_i \text{:}

\text{For } i = 1:
y_1 = \sum_{j=1}^3 a_{1j}x_j = a_{11}x_1 + a_{12}x_2 + a_{13}x_3 = 1x_1 + 2x_2 + 3x_3

\text{For } i = 2:
y_2 = \sum_{j=1}^3 a_{2j}x_j = a_{21}x_1 + a_{22}x_2 + a_{23}x_3 = 4x_1 + 5x_2 + 6x_3

\text{For } i = 3:
y_3 = \sum_{j=1}^3 a_{3j}x_j = a_{31}x_1 + a_{32}x_2 + a_{33}x_3 = 7x_1 + 8x_2 + 9x_3

\text{Therefore, the result of } Ax \text{ is:}

Ax = \begin{bmatrix}
1x_1 + 2x_2 + 3x_3 \\
4x_1 + 5x_2 + 6x_3 \\
7x_1 + 8x_2 + 9x_3
\end{bmatrix}$$

In [42]:
arr_1 = np.array([[1],[1],[0]]).T
arr_2 = np.array([[0],[1],[1]]).T

In [43]:
arr_1.shape

(1, 3)

In [44]:
arr_2

array([[0, 1, 1]])

In [45]:
arr_1 * arr_2

array([[0, 1, 0]])

In [46]:
np.cross(arr_1, arr_2)

array([[ 1, -1,  1]])