In [14]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

np.set_printoptions(suppress=True, precision=4)


### Notes: 

$A\mathbf{x} = \mathbf{b}$ -> has exactly one solution for this space $\mathbf{x} = A^{-1}b$

In [15]:
A = np.array([[2,3,1],[2,4,1],[3,7,1]])
A

array([[2, 3, 1],
       [2, 4, 1],
       [3, 7, 1]])

Invertible Matrix

In [16]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 3., -4.,  1.],
       [-1.,  1., -0.],
       [-2.,  5., -2.]])

Dot product of the original matrix and its inverse should produce an identity matrix

In [17]:
A @ A_inv

array([[ 1., -0.,  0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])

#### Using `solve`

This is the more computationally efficient way, as matrices grow in size

In [23]:
n = A.shape[0]
n

3

In [25]:
A_id = np.eye(n)

In [26]:
np.linalg.solve(A, A_id)

array([[ 3., -4.,  1.],
       [-1.,  1., -0.],
       [-2.,  5., -2.]])

**Problems for Lecture 1 (from textbook Section I.1)**

1. Give an example where a combination of three nonzero vectors in $\mathbb{R}^4$ is the zero vector. Then write your example in the form $A\mathbf{x} = \mathbf{0}$. What are the shapes of $A$ and $\mathbf{x}$ and $\mathbf{0}$?

4. Suppose $A$ is the $3 \times 3$ matrix $\text{ones}(3, 3)$ of all ones. Find two independent vectors $\mathbf{x}$ and $\mathbf{y}$ that solve $A\mathbf{x} = \mathbf{0}$ and $A\mathbf{y} = \mathbf{0}$. Write that first equation $A\mathbf{x} = \mathbf{0}$ (with numbers) as a combination of the columns of $A$. Why don't I ask for a third independent vector with $A\mathbf{z} = \mathbf{0}$?

9. Suppose the column space of an $m \times n$ matrix is all of $\mathbb{R}^3$. What can you say about $m$? What can you say about $n$? What can you say about the rank $r$?

18. If $A = CR$, what are the $CR$ factors of the matrix $A^T$?